"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

function todayIsoDate(): string {
  return new Date().toISOString().slice(0, 10);
}

function daysAgoIsoDate(days: number): string {
  const now = new Date();
  now.setUTCDate(now.getUTCDate() - days);
  return now.toISOString().slice(0, 10);
}

type GeneratedBrief = {
  id: string;
  startDate: string;
  endDate: string;
  generatedAt: string;
  generatedBy?: string | null;
  snapshot?: {
    summary: {
      opportunityCount: number;
    };
  };
};

export default function BriefGeneratorPage() {
  const defaultStartDate = useMemo(() => daysAgoIsoDate(6), []);
  const defaultEndDate = useMemo(() => todayIsoDate(), []);

  const [startDate, setStartDate] = useState(defaultStartDate);
  const [endDate, setEndDate] = useState(defaultEndDate);
  const [generatedBy, setGeneratedBy] = useState("pm");
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [lastGeneratedBrief, setLastGeneratedBrief] = useState<GeneratedBrief | null>(null);
  const [recentBriefs, setRecentBriefs] = useState<GeneratedBrief[]>([]);
  const [isLoadingBriefs, setIsLoadingBriefs] = useState(true);

  async function loadRecentBriefs() {
    setIsLoadingBriefs(true);
    try {
      const response = await fetch("/api/briefs?limit=10", {
        cache: "no-store"
      });
      const payload = (await response.json()) as { error?: string; briefs?: GeneratedBrief[] };
      if (!response.ok || !payload.briefs) {
        throw new Error(payload.error ?? "Failed to load recent briefs.");
      }

      setRecentBriefs(payload.briefs);
    } catch (loadError) {
      setError(loadError instanceof Error ? loadError.message : "Failed to load recent briefs.");
    } finally {
      setIsLoadingBriefs(false);
    }
  }

  useEffect(() => {
    void loadRecentBriefs();
  }, []);

  async function onGenerate() {
    setIsSubmitting(true);
    try {
      const response = await fetch("/api/briefs/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          startDate: `${startDate}T00:00:00.000Z`,
          endDate: `${endDate}T23:59:59.999Z`,
          generatedBy: generatedBy.trim() || undefined
        })
      });

      const payload = (await response.json()) as { error?: string; brief?: GeneratedBrief };
      if (!response.ok || !payload.brief) {
        throw new Error(payload.error ?? "Failed to generate weekly brief.");
      }

      setLastGeneratedBrief(payload.brief);
      await loadRecentBriefs();
      setError(null);
    } catch (submitError) {
      setError(submitError instanceof Error ? submitError.message : "Failed to generate weekly brief.");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <main className="mx-auto max-w-3xl px-6 py-12">
      <div className="mb-7">
        <h1 className="text-2xl font-semibold text-slate-900">Weekly Brief Generator</h1>
        <p className="mt-2 text-sm text-slate-700">
          Generate an immutable weekly snapshot using approved opportunities only.
        </p>
      </div>

      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
        <div className="grid gap-4 sm:grid-cols-2">
          <label className="text-sm">
            <span className="mb-1 block text-slate-700">Start date</span>
            <input
              type="date"
              className="w-full rounded border border-slate-300 px-3 py-2"
              value={startDate}
              onChange={(event) => setStartDate(event.target.value)}
            />
          </label>
          <label className="text-sm">
            <span className="mb-1 block text-slate-700">End date</span>
            <input
              type="date"
              className="w-full rounded border border-slate-300 px-3 py-2"
              value={endDate}
              onChange={(event) => setEndDate(event.target.value)}
            />
          </label>
        </div>

        <label className="mt-4 block text-sm">
          <span className="mb-1 block text-slate-700">Generated by (optional)</span>
          <input
            type="text"
            className="w-full rounded border border-slate-300 px-3 py-2"
            value={generatedBy}
            onChange={(event) => setGeneratedBy(event.target.value)}
          />
        </label>

        <div className="mt-5">
          <button
            type="button"
            className="rounded bg-sky-700 px-4 py-2 text-sm font-medium text-white disabled:bg-slate-400"
            disabled={isSubmitting}
            onClick={() => {
              void onGenerate();
            }}
          >
            {isSubmitting ? "Generating..." : "Generate Brief"}
          </button>
        </div>

        {error ? (
          <p className="mt-4 rounded border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</p>
        ) : null}
      </section>

      {lastGeneratedBrief ? (
        <section className="mt-6 rounded-xl border border-emerald-200 bg-emerald-50 p-5">
          <p className="text-sm text-emerald-900">
            Generated brief <span className="font-semibold">{lastGeneratedBrief.id}</span>
          </p>
          <Link href={`/briefs/${lastGeneratedBrief.id}`} className="mt-2 inline-block text-sm text-sky-700 underline">
            Open brief snapshot
          </Link>
        </section>
      ) : null}

      <section className="mt-6 rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
        <h2 className="text-sm font-semibold uppercase tracking-wide text-slate-700">Recent Briefs</h2>
        {isLoadingBriefs ? <p className="mt-3 text-sm text-slate-600">Loading recent briefs...</p> : null}
        {!isLoadingBriefs && recentBriefs.length === 0 ? (
          <p className="mt-3 text-sm text-slate-600">No briefs generated yet.</p>
        ) : null}
        <ul className="mt-3 space-y-2">
          {recentBriefs.map((brief) => (
            <li key={brief.id} className="rounded border border-slate-200 p-3 text-sm">
              <p className="font-medium text-slate-900">{brief.id}</p>
              <p className="text-xs text-slate-600">
                Range: {brief.startDate.slice(0, 10)} to {brief.endDate.slice(0, 10)}
              </p>
              <p className="text-xs text-slate-600">Generated: {new Date(brief.generatedAt).toLocaleString("en-US")}</p>
              <Link href={`/briefs/${brief.id}`} className="mt-1 inline-block text-xs text-sky-700 underline">
                Open snapshot
              </Link>
            </li>
          ))}
        </ul>
      </section>
    </main>
  );
}
